"""Canonical trajectory data contract shared across agents."""

from .actions import (
    Action,
    CanonicalActionError,
    ClickAction,
    DragAction,
    HotkeyAction,
    KeyTransitionAction,
    MouseButtonTransitionAction,
    NoOpAction,
    MoveAction,
    ScrollAction,
    SequenceAction,
    ShellAction,
    TerminateAction,
    TypeAction,
    WaitAction,
    action_from_dict,
    action_to_dict,
)

__all__ = [
    "Action",
    "CanonicalActionError",
    "ClickAction",
    "DragAction",
    "HotkeyAction",
    "KeyTransitionAction",
    "MouseButtonTransitionAction",
    "NoOpAction",
    "MoveAction",
    "ScrollAction",
    "SequenceAction",
    "ShellAction",
    "TerminateAction",
    "TypeAction",
    "WaitAction",
    "action_from_dict",
    "action_to_dict",
]
